#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"
require "pal"

include Pal::Configuration
include Pal::Log

request_config = Config.new

OptionParser.new do |opts|
  opts.banner = "Usage: pal_cli [options]"

  opts.on("-t", "--template_file=template_file", "Template definition file") do |t|
    request_config.template_file_loc = t
  end

  opts.on("-s", "--source_file=source_file", "Source file") do |s|
    request_config.source_file_loc = s
  end

  opts.on("-o", "--output_dir=output_dir", "Output directory") do |o|
    request_config.output_dir = o
  end

  opts.on("-h", "--help", "Prints this help") do
    puts opts
    exit
  end
end.parse!

begin
  request_config.validate
rescue Pal::ValidationError
  log_error("The request provided was invalid, please fix the validation errors and try again.")
  return
end

log_info "Config loaded successfully"
main = Pal::Main.new(request_config)

log_info "Setting up runbooks to be processed ..."
main.setup

log_info "... set up complete. Beginning process"
main.process
